# Error bars

Given the formula that links the differential cross section to the event rate measured by our experiment:

$$
\frac{dR}{d \Omega_{spect}} = \epsilon_{spect}\left(\theta \right) \cdot \frac{n_{gate}}{T} \cdot n_{c} \cdot \wp(\theta; \lambda', \lambda '') \cdot \frac{d \sigma}{d \Omega}
$$

with our equipment we were able to measure just the rate of events for a certain scattering angle, not the differential quantity $\frac{dN}{d \Omega}$, the formula above is then replaced by:

$$
dR = d \Omega_{spect} \cdot \epsilon_{spect}\left(\theta \right) \cdot \frac{n_{gate}}{T} \cdot n_{c} \cdot \wp(\theta; \lambda', \lambda '') \cdot \frac{d \sigma}{d \Omega}
$$

once settled this key concept it is crucial to correctly evaluate the uncertainities linked to these measurements. 

## Statistical and systematical uncertainties + work flow
First thing first it is fundamental to distinguish between the various sources of errors one can come across during a measurement in a nuclear physics' experiment.
In particular we need to separate the contributions given by $\textit{statistical}$ and $\textit{systematical}$ uncertainties:

- Statistical uncertainities could come from the counting of photons or the errors associated to the fit parameters, a square sum will be used to take account of them.
- Systematical uncertainties arise from various effects, such as the shift of the Compton peak, the errors associated with the geometrical measurements of the apparatus and so on, we'll take account of them with a square sum as well.

By looking at the expression above one could come up with an expression for the uncertainty that looks like:

$$
\left(\frac{\delta R}{R} \right) = \left(\frac{\delta (d \Omega_{spect})}{d \Omega_{spect}} \right) \oplus \left(\frac{\delta \epsilon_{spect}}{\epsilon_{spect}} \right) \oplus \left(\frac{\delta n_{gate}}{n_{gate}} \right) \oplus \left(\frac{\delta n_c}{n_c} \right) \oplus \left(\frac{\delta \wp}{\wp} \right) 
$$

assuming every quantity considered in this expression is independent from one another and has a relatively small error associated to it.

To make sure randomness and bias are not mixed together these two kinds of uncertainties will be combined as:

$$
\sigma_{tot} = \sigma_{statistic} + \sigma_{systematic}
$$

so that one can split the two contributes in:

$$ \left(\frac{\delta Q_{stat}}{Q} \right)^2 = \sum_{X \, \in \, (d \Omega_{spect}, \epsilon_{spect}, n_{gate}, n_c, \wp)}  \left(\frac{\delta X_{stat}}{X} \right)^2 $$
$$ \left(\frac{\delta Q_{sist}}{Q} \right)^2 = \sum_{X \, \in \, (d \Omega_{spect}, \epsilon_{spect}, n_{gate}, n_c, \wp)}  \left(\frac{\delta X_{sist}}{X} \right)^2 $$


## $n_c$ uncertainty

Given:

$$
n_c = \rho \frac{N_a \cdot Z}{MM}
$$

where: 
- $\rho$ is the density of the scattering target
- $N_a$ is the Avogadro number
- $\text{MM}$ is the molar mass of the scattering target

One can clearly see that all these quantities are known with extreme accuracy, we won't take account of their uncertainties.

## $\epsilon_{spect}$ uncertainty

In this case the value of $\epsilon_{spect}$ is obtained by an interpolation, the error associated to it will then be consider as a statistical uncertainty. Given the formula used to fit the efficiency curve: 

$$
\epsilon_{spect} = A \cdot E^{-B} \cdot \exp(-C \cdot E) + D
$$

where $A,B,C,D$ are all model parameters and $E$ is the energy of the incoming gamma ray. Given that, one can compute the error associated to this quantity as:

$$
\delta \epsilon = \left( \frac{\partial \epsilon}{\partial A} \cdot \delta A \right) \oplus \left( \frac{\partial \epsilon}{\partial B} \cdot \delta B \right) \oplus \left( \frac{\partial \epsilon}{\partial C} \cdot \delta C \right) \oplus \left( \frac{\partial \epsilon}{\partial D} \cdot \delta D \right)
$$

$$
\delta \epsilon = \sqrt{\left[E^{-B} \cdot e^{-CE} \cdot \delta A \right]^2 + \left[A \cdot E^{-B} \cdot e^{-CE} \cdot \ln(B) \cdot \delta B \right]^2 + \left[A \cdot E^{-B} \cdot e^{-CE} \cdot E \cdot \delta C \right]^2 + \left[ \delta D \right]^2}
$$



In [1]:
import numpy as np

# Parametri del fit e le relative incertezze
A = 1.5604
delta_A = 1.2255

B = -0.0995
delta_B = 0.04328

C = 3.53466
delta_C = 1.00558

D = 0.10210
delta_D = 0.00978

def epsilon_spettrometer(theta): 

    A = 1.5604
    B = -0.0995
    C = 3.53466
    D = 0.10210
    
    E  = 511/(2 - np.cos(theta)) * 1e-3 #da MeV a keV

    return A * pow(E, -B) * np.exp(-C * E) + D


def delta_eff(E):
    term1 = E**(-2 * B) * np.exp(-2 * C * E) * delta_A**2
    term2 = A**2 * E**(-2 * B) * np.exp(-2 * C * E) * (np.log(E))**2 * delta_B**2
    term3 = A**2 * E**(-2 * B) * np.exp(-2 * C * E) * (E**2) * delta_C**2 
    term4 = delta_D**2

    delta_epsilon = np.sqrt(term1 + term2 + term3 + term4)
    return delta_epsilon

E_input = 511 
result = delta_eff(E_input)
print(f"\nIncertezza sull'efficienza (δϵ) a E = {E_input:.2f} è {result:.6f}")



Incertezza sull'efficienza (δϵ) a E = 511.00 è 0.009780


## $n_{gate}$ uncertainty

Given: 

$$
n_{gate} = 2 \cdot S \left(t \right) \cdot \text{BR} \cdot \frac{\Delta\Omega}{4\pi} \cdot \epsilon_{gate}(511)
$$

where: 
- $S(t)$ is the activity of the source in Bq
- $\text{BR}$ is the branching ratio of the 511 keV photon
- $\frac{\Delta\Omega}{4\pi}$ is the solid angle
- $\epsilon_{gate}(511)$ is the efficiency of the gate detector for the 511 keV photon

In this case one can assume that the branching ratio (BR) is well known, the uncertainties linked to $S \left(t \right)$ and $\epsilon_{gate}$ are statistical errors and the one associated to $\Delta \Omega$ is systematical.

### $\delta S(t)$ computation
For this uncertainty, an error of 0.5 cm in the distance from the detector and 3 mm in the displacement from the detector axis was considered. The acquisition times were assumed to be error-free, as they were set within the Maestro application. For the number of counts, the uncertainty associated with Poisson statistics was taken into account.
The associated error is then:

$$
\delta S \left( t \right) = 11647 \ Bq.
$$

### $\delta \epsilon_{gate}$ computation

For this computation please refer to the previous section.
We impose a 2.5% error on each point and from the linear fit we gain:

$$
\delta \epsilon_{gate} (511) = 0.01672   
$$

### $\delta (\Delta \Omega / 4\pi)$ computation

For the uncertainty linked to the measurement of the solid angle covered by the spectrometer one can start from the formula:

$$
\frac{\Delta\Omega}{4\pi} =  \frac{1 - \cos (\beta)}{2}
$$

where $\beta$ is computed as: 

$$
\beta = \arctan \left( \frac{r_{gate}}{d_{source-gate}} \right).
$$

Both of these two measurements are known with their uncertainty, $r_{gate} = (1,27 \pm 0,01) \, cm$ and ${d_{source-gate}} = d =(18.54 \pm 0.5) \, cm$, knowing that one can propagate the errors using the error propagation expression.

$$
\left(\delta (\Delta \Omega / 4\pi) \right) = \left( \frac{\partial (\Delta \Omega / 4\pi)}{\partial r} \delta r\right) \oplus \left( \frac{\partial (\Delta \Omega / 4\pi)}{\partial d} \delta d\right)
$$

and that:

$$
\frac{\partial (\Delta \Omega / 4\pi)}{\partial r} = \frac{r}{2 d^2 \cdot \left( \frac{r^2}{d^2} + 1 \right)^{3/2}}
$$

$$
\frac{\partial (\Delta \Omega / 4\pi)}{\partial d} = - \frac{r^2}{2 d^3 \cdot \left( \frac{r^2}{d^2} + 1 \right)^{3/2}}
$$

one can find the uncertainty asssociated to the solid angle using the formula below:

$$
\delta \left(\Delta \Omega / 4\pi \right) = \sqrt{\left(\frac{r}{2 d^2 \cdot \left( \frac{r^2}{d^2} + 1 \right)^{3/2}} \cdot \delta r \right)^2 + \left(\frac{r^2}{2 d^3 \cdot\left( \frac{r^2}{d^2} + 1 \right)^{3/2}} \cdot \delta d \right)^2}
$$


In [2]:
import math

# Valori noti (convertiti in metri se vuoi usare il SI, qui rimangono in cm)
r = 1.27       # cm
delta_r = 0.01 # cm
d = 18.54       # cm
delta_d = 0.5  # cm

term1  = r * delta_r / (2 * d**2 * (r**2/d**2 + 1)**(3/2))
term2 = r**2 * delta_d / (2 * d**3 * (r**2/d**2 + 1)**(3/2))

delta_Omega = np.sqrt(term1**2 + term2**2)

Omega = 2 * np.pi * (1-np.cos(np.arctan(r/d)))

print(f"Incertezza sulla frazione di angolo solido ΔΩ/4π:",Omega ,"+/-", delta_Omega)


Incertezza sulla frazione di angolo solido ΔΩ/4π: 0.01468969384187046 +/- 6.545346664430829e-05


## $d \Omega_{spect}$ uncertainty

In questa sezione faccio riferimento al disegno che ha fatto Andre per il calcolo dell'angolo solido.

Since we are computing a solid angle, the formula used to compute it is the same as always:

$$
d \Omega = 2 \pi \cdot \left( 1 - \cos \beta \right)
$$

where $\beta$ is now given from the Carnot theorem that states:

$$
A^2 + B^2 + 2AB \cos \beta = C^2.
$$

Givent that, one can easily compute $\cos \beta$ with the inverse formula:

$$
\cos \beta = \frac{A^2 + B^2 - C^2}{2AB}.
$$

In this case $C$ is known from the Scionix manual and so is the error associated to it $\delta C$ while $A$ and $B$ are computed as:

- $A = d(IP, D_a) = \sqrt{\sum_{j=1}^{3} \left(IP_j - D_{a_j}\right)^2}$
- $B = d(IP, D_b) = \sqrt{\sum_{j=1}^{3} \left(IP_j - D_{b_j}\right)^2}$

where $IP$ stands for "Interaction Point", indicating the place where the Compton interaction has taken place, it is defined as $IP = (x, y, z)$ and its uncertainty is given by the spatial resolution of our simulation $\delta x = \delta y = \delta z = 0.25 \, mm$. $A$ and $B$ are the segments linking $IP$ to the spectrometer's edge respectively $D_a$ and $D_b$, known from a geometrical reasoning and considered without uncertainty. \\
For A the error can be computed starting from the partial derivative:

$$
\frac{\partial A}{\partial IP_j} = \sqrt{\sum_{k=1}^{3} \left(IP_k - D_{a_k}\right)^2} = \frac{IP_j - D_{a_j}}{A}. 
$$

assuming the uncertainties between x, y and z are uncorrelated and $ \delta_x = \delta_y = \delta_z = \delta$ one can write the error propagation formula as:

$$
\delta_A^2 = \sum_{k=1}^{3} \left(\frac{\partial A}{\partial IP_k} \cdot \delta_k \right)^2 = \delta^2 \frac{1}{A^2} \sum_{k=1}^{3} \left( IP_k - D_{a_j}\right)^2.
$$

But since $A$ was previously defined as $ A = \sqrt{\sum_{j=1}^{3} \left(IP_j - D_{a_j}\right)^2}$, one can then write the following:

$$
\delta_A = \delta.
$$

Obviously the same goes for $\delta_B = \delta$.
Since $\delta_A = \delta_B = \delta$ are known and $\delta_C$ comes from the Scionix manual, following:

$$
\delta_{\cos \beta} = \left( \frac{\partial \cos \beta}{\partial A} \right) \oplus \left( \frac{\partial \cos \beta}{\partial B} \right) \oplus \left( \frac{\partial \cos \beta}{\partial C} \right)
$$

where: 

- $\frac{\partial \cos \beta}{\partial A} = \frac{A^2 - B^2 + C^2}{2A^2B}$
- $\frac{\partial \cos \beta}{\partial B} = \frac{B^2 - A^2 + C^2}{2AB^2}$
- $\frac{\partial \cos \beta}{\partial B} = - \frac{C}{AB}$

one can finally come up with an expression for the error propagation on the quantity $\cos \beta$:

$$
\delta_{\cos \beta} = \sqrt{\left(\frac{A^2 - B^2 + C^2}{2A^2B} \right)^2 \cdot \delta^2 + \left(\frac{B^2 - A^2 + C^2}{2AB^2} \right)^2 \cdot \delta^2 + \left(\frac{C}{AB} \right)^2 \cdot \delta_C^2}
$$




## Final results

Knowing all the information we need, the uncertainty on the rate measurement can be expressed as:

$$
\frac{\delta R}{R} = \left[ \left(\frac{\delta \epsilon_{spectrometer}}{\epsilon_{spectrometer}} \right) \oplus \left(\frac{\delta S(t)}{S(t)} \right) \oplus \left(\frac{\delta \epsilon_{gate}}{\epsilon_{gate}} \right) \right] \pm \left( \frac{\delta \Delta \Omega}{\Delta \Omega} \right)
$$



In [3]:
def leggi_dati(file_path):
    # Inizializza liste per ogni colonna
    angle, rate, err_rate = [], [], []
    count, err_count = [], []
    channel, err_channel = [], []
    sigma, err_sigma = [], []

    with open(file_path, 'r') as file:
        lines = file.readlines()

        # Salta l'intestazione
        for line in lines[1:]:
            valori = line.strip().split()
            if len(valori) != 9:
                continue  # Salta righe non valide

            angle.append(float(valori[0]))
            rate.append(float(valori[1]))
            err_rate.append(float(valori[2]))
            count.append(float(valori[3]))
            err_count.append(float(valori[4]))
            channel.append(float(valori[5]))
            err_channel.append(float(valori[6]))
            sigma.append(float(valori[7]))
            err_sigma.append(float(valori[8]))

    return angle, rate, err_rate, count, err_count, channel, err_channel, sigma, err_sigma

file_path = "../Codes/data_analysis/parameters_pol4_riflection.txt"

angle, rate, err_rate, count, err_count, channel, err_channel, sigma, err_sigma = leggi_dati(file_path)

file_path = "../Codes/data_analysis/parameters_pol4_trasmission.txt"

angle_trasm, rate_trasm, err_rate_trasm, count_trasm, err_count_trasm, channel_trasm, err_channel_trasm, sigma_trasm, err_sigma_trasm = leggi_dati(file_path)


In [4]:
# Dati tabella: angoli in gradi e valori corrispondenti
# angles_deg = np.array([
#     140, 135, 130, 125, 120, 115, 110, 105, 100, 95,
#     90, 85, 80, 75, 70, 65, 60, 55, 50, 45,
#     40, 35, 30, 25, 20
# ])

# #N.B. PER IL 35 HO USATO IL VALORE IN TRASMISSIONE A 45 CM 
# values = np.array([
#     0.03244310169, 0.03244310169, 0.03249877382, 0.03249877382, 0.03249877382,
#     0.03244310169, 0.03244310169, 0.03249877382, 0.03249877382, 0.03249877382,
#     0.03244310169, 0.03244310169, 0.03244310169, 0.03244310169, 0.03244310169,
#     0.03255449356, 0.03255449356, 0.03261026089, 0.03261026089, 0.0327778485,
#     0.03288981157, 0.03300196504, 0.03322684314, 0.03345248278, 0.03384918453,
#     0.03436265618, 0.03522700787, 0.03669138374, 0.03964779781, 0.04777407735
# ]) 

angles_deg_ref = np.array([40, 50, 60, 70, 80, 90, 100, 110])
values_ref = np.array([0.02735079041747454, 0.025819652026622272, 0.027070509615309143, 
                   0.026302777950659273, 0.026575610155933342, 0.02669072072779364,
                   0.026320830435048827, 0.02677502814759899])

angles_deg_trasm = np.array([35, 40, 50, 60])
values_trasm = np.array([0.026686807818702276, 0.02735079041747454, 0.025819652026622272, 0.027070509615309143])

# def angle_spectrometer(theta, angles_deg):
#     # Converti radianti in gradi
#     angle_deg = np.degrees(theta)
    
#     # Trova indice del valore con angolo più vicino
#     idx = (np.abs(angles_deg - angle_deg)).argmin()
    
#     # Restituisci il valore corrispondente
#     return idx

# # Calcola i valori corrispondenti di angle_spectrometer per ogni angolo
# spectrometer_values = np.array([angle_spectrometer(theta, angles_deg_ref) for theta in angles_deg_ref])

# Dividi ogni rate per il corrispondente valore di angle_spectrometer
corrected_rates = rate / values_ref

# spectrometer_values_trasm =  np.array([angle_spectrometer(theta, angles_deg_trasm) for theta in angles_deg_trasm]) # rispettivamente 35 ,40 ,50 deg

corrected_rates_trasm = rate_trasm / values_trasm

In [5]:
S = 188900
dS = 11647

print (" attività" , dS/S)

E = 0.14700
dE =0.01672  

print("\n efficienza gate", dE/E)


dOmega = delta_Omega

print("\n frazione di angolo solido", dOmega/Omega)



angles = np.radians(angle)
energies = 511/(2 - np.cos(angles))
efficiencies = epsilon_spettrometer(angles)
err_tot = corrected_rates * (
    np.sqrt((dS / S)**2 + (dE / E)**2 + (delta_eff(energies) / efficiencies)**2) + dOmega / Omega
)

print("\n efficienza spettrometro _ riflex", delta_eff(energies) / efficiencies)



#------------------------

angles_trasm = np.radians(angle_trasm)
energies_trasm = 511/(2 - np.cos(angles_trasm))
efficiencies_trasm = epsilon_spettrometer(angles_trasm)
err_tot_trasm = corrected_rates_trasm * (
    np.sqrt((dS / S)**2 + (dE / E)**2 + (delta_eff(energies_trasm) / efficiencies_trasm)**2) + dOmega / Omega
)

print("\n efficienza spettrometro _ trasm",delta_eff(energies_trasm) / efficiencies_trasm)

print("\n\n\n\n")

print(err_tot)
print(err_tot_trasm)


 attività 0.061656961355214396

 efficienza gate 0.11374149659863945

 frazione di angolo solido 0.0044557406947273726

 efficienza spettrometro _ riflex [0.0225969  0.02053506 0.01871464 0.0171871  0.01594345 0.0149484
 0.01416031 0.01354058]

 efficienza spettrometro _ trasm [0.02367513 0.0225969  0.02053506 0.01871464]





[0.08643795 0.22810205 0.1811194  0.12720782 0.07477297 0.13297517
 0.06668744 0.07411656]
[0.11663566 0.09875077 0.07444269 0.05318229]


# Energy uncertainties

On the x-axis of our Klein-Nishina plot we put the scattering angles, linked to these quantities there are a few uncertainty factors such as:
- The shift in the position of the Compton peak due to temperature instability and other environmental factors.
- The error associated to the measurement of the scattering angle. 
- The uncertainty linked to the spectrometer resolution, which, of course, is not ideal.
- The statistic error derived from the gaussian fit of the Compton peak.

While these first three factors have a systematic nature, the last one can be considered as strictly statistical. Knowing this it is crucial to transform every energy-related quantity into an angle-related quantity, one can do that simply by using the inverted Compton formula shown below:

$$
\theta (E') = \arccos \left[2- \frac{511}{E'} \right]
$$

that gives rise to the associated uncertainty formula, which is:

$$
\delta \theta = \left |\frac{511}{E'^2 \cdot \sqrt{1 - \left(2 - \frac{511}{E'} \right)^2}} \right | \cdot \delta E' 
$$







## Peak shift uncertainty

Knowing that the Compton peak undergoes a mean fluctuation called $\Delta E_{peak} = 8 \, ch = 24 \, keV$, we used $\delta E_{peak} = \frac{\Delta E_{peak}}{2} = 4 \, ch = 12 \,keV$ to quantify our peak energy uncertainty. This can be expressed as:

$$
\delta \theta_{peak} = \left |\frac{511}{E'^2 \cdot \sqrt{1 - \left(2 - \frac{511}{E'} \right)^2}} \right | \cdot \delta E_{peak}  .
$$

In [6]:
dE = 12 #keV
dThetaPeak =np.array([])

for i in range(len(energies)):
    dTheta = 511/(energies[i]**2 * np.sqrt(1 - (2 - 511/energies[i])**2)) * dE
    dThetaPeak = np.append(dThetaPeak, dTheta)
print(dThetaPeak)

dThetaPeak_trasm = np.array([])
for i in range(len(energies_trasm)):
    dTheta = 511/(energies_trasm[i]**2 * np.sqrt(1 - (2 - 511/energies_trasm[i])**2)) * dE
    dThetaPeak_trasm = np.append(dThetaPeak_trasm, dTheta)
print(dThetaPeak_trasm)

[0.0556278  0.05646795 0.06101157 0.06869625 0.07953857 0.09393346
 0.11266458 0.13707422]
[0.0570896  0.0556278  0.05646795 0.06101157]


## Scattering angle uncertainty

This is chosen besed on the instrumental error used to measure $\theta_{scattering}$, and it is called $\delta \theta_{scattering}$.

Assuming $a = 5 \, deg$ one can compute the error assocaited to the placement of the detector at a given scattering angle as:

$$
\delta \theta_{scattering} = \frac{a}{\sqrt{12}}
$$


In [7]:
dThetaScattering = (5 * np.pi/180) / np.sqrt(12)
print(dThetaScattering)

0.02519165783658636


## Resolution uncertainty

The error due to the resolution of a detector can be expressed by means of the percentile resolution of our spectrometer, that can be computed as:

$$
\delta_{resolution} = \frac{2.35 \cdot \sigma_{fit}}{channel} \cdot 100
$$

Just like the previous case, this quantity needs to be expressed in terms of the scattering angle, this can be computed using:

$$
\delta \theta_{resolution} = \left| \frac{1}{sin^2 \theta \cdot (E')^2}\right| \cdot \delta_{resolution} 
$$

In [8]:

dThetaRis = 1/(np.sin(angles)**2 * (energies**2)) * err_sigma * 2.35 / angles * 100
print(dThetaRis)

dThetaRis_trasm = 1/(np.sin(angles_trasm)**2 * (energies_trasm**2)) * err_sigma_trasm * 2.35 / angles_trasm * 100
print(dThetaRis_trasm)

[0.00285039 0.00197468 0.00278447 0.00119245 0.00146308 0.00130629
 0.00155746 0.00145591]
[0.00611945 0.00475065 0.00326955 0.00376419]


## Statistical uncertainty

The error derived solely from the fit of the Compton peak can be taken in account with the formula:

$$
\delta_{fit} = \frac{\sigma_{fit}}{\sqrt{N}}
$$

Where N is the number of elements in my Compton peak, here as well one needs to express this error in terms of the scattering angle, the formula used is the same:

$$
\delta \theta_{fit} = \left| \frac{1}{sin^2 \theta \cdot (E')^2}\right| \cdot \delta_{fit}.
$$

In [9]:
dThetaFit = 1/(np.sin(angles)**2 * (energies**2)) * err_sigma / np.sqrt(count)
print(dThetaFit)

dThetaFit_trasm = 1/(np.sin(angles_trasm)**2 * (energies_trasm**2)) * err_sigma_trasm / np.sqrt(count_trasm)
print(dThetaFit_trasm)

[6.45345418e-08 6.43978028e-08 1.19067243e-07 4.74724502e-08
 8.91584160e-08 6.96607856e-08 1.18455093e-07 1.23204113e-07]
[1.35513929e-07 1.60857662e-07 1.16761642e-07 2.17387811e-07]


## Final results

One can express the error bars on the x-axis as a sum of statistical and systematical uncertainties following the expression:

$$
\delta \theta = \delta \theta_{stat} \pm \delta \theta_{syst} = (\delta \theta_{fit}) \pm \left(\delta \theta_{peak} \oplus \delta \theta_{scattering} \oplus \delta \theta_{resolution} \right)
$$

In [10]:
dThetaTOT = dThetaFit + np.sqrt(dThetaPeak**2 + dThetaRis**2 + dThetaScattering**2)
print (dThetaTOT)

dThetaTOT_trasm = dThetaFit_trasm + np.sqrt(dThetaPeak_trasm**2 + dThetaRis_trasm**2 + dThetaScattering**2)
print(dThetaTOT_trasm)

[0.06113268 0.06186401 0.06606664 0.07317939 0.08344555 0.09726168
 0.11545726 0.1393776 ]
[0.06270013 0.0612508  0.06191892 0.06611528]


In [11]:
np.savez('errori_arrays_riflex.npz', y_err=err_tot, x_err=dThetaTOT)
np.savez('errori_arrays_trasm.npz', y_err=err_tot_trasm, x_err=dThetaTOT_trasm)

print("File 'errori_arrays.npz' salvato con successo.")

File 'errori_arrays.npz' salvato con successo.
